### ISSUE TITLE
Build artifacts should have the source infomation

### ISSUE THREAD

**Issue by manuranga** [wso2/carbon-uuf-maven-tools#50]
In the build artifact inside each `component` and `theme` there should be a file (eg `.build`) that has the current source repo and the revision (like http://www.mojohaus.org/buildnumber-maven-plugin/usage.html)

Ideally one should be able to see a link in debugger view to each fragment/page's source.

**Comment by this** [comment]
@manuranga Build artifacts of UUF components, and themes are identical (UUF Maven plugin might generate one or two files e.g. `osgi-imports`, but it never deletes) to their source directory. So, I don't see a necessity of this feature.

**Comment by manuranga** [comment]
Objective is not to look at the code, objective is to find where to patch for a support issue.

**Comment by this** [comment]
Closing as repo is [deprecated](https://github.com/wso2/carbon-uuf-maven-tools/pull/89).
