### ISSUE TITLE
Make UUF apps shareable with other UUF apps

### ISSUE THREAD

**Issue by tmkasun** [wso2/carbon-uuf-maven-tools#52]
We have an use case that, we need to share pages in between `Publisher` and `Editor` UUF apps (Not just a fragment but the whole page).Currently, what we can do is create a fragment using the HTML content of the create page and put it in a common component which has dependencies in both editor and publisher app.Then include the fragment in both editor and publisher app.
The above approach will still duplicate `layout` , `fillzone` and another element in base `create.hbs` file.
So what I suggest is, Make the app itself shareable with other apps, so that we can put one app(`Editor`) depends on another app(`Publisher`), Where pages of the depending app will be copied to the dependant at the build time by the maven plugin.
@this Could you please consider about this feature when working for the next release.
Thanks
~TMKasun

**Comment by this** [comment]
Closing as repo is [deprecated](https://github.com/wso2/carbon-uuf-maven-tools/pull/89).
