### ISSUE TITLE
P2.inf in app has instructions.unconfigure

### ISSUE THREAD

**Issue by Niranjan-K** [wso2/carbon-uuf-maven-tools#85]
When an app is created using the maven archtype, it creates the below:

instructions.unconfigure = \
org.eclipse.equinox.p2.touchpoint.natives.remove(path:${installFolder}/../../deployment/uufapps/org.wso2.carbon.uuf.sample.myapp);\

In C5, we have two deployment folder, that is customer deployment folder and (server) runtime specific deployment folder. Therefore when we uninstall, as per the above from above, how do we specify from where the feature needs to be remove. 

App for customer deployment folder is enough to be installed in one runtime since it is outside the runtime but in the case of runtime specific app, it needs to be installed to all the runtimes.

**Comment by this** [comment]
Closing as repo is [deprecated](https://github.com/wso2/carbon-uuf-maven-tools/pull/89).
